<?php echo $this->doctype(); ?>

<html lang="en" ng-app="taskApp">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Task Tracker') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/bower_components/angular/angular.js'))
            ->prependFile($this->basePath('js/bower_components/jquery/dist/jquery.js'))
        ; ?>

    </head>
    <body ng-controller="TaskController">
      <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <a href="#" class="navbar-brand">Task Tracker</a>
            </div>
          </div>
      </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
