<?php
    $this->headScript()->prependFile($this->basePath('js/index.js'))
?>
<h1>Tasks</h1>
<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>Due Date</th>
        <tr>
    </thead>
    <tbody ng-init="tasks = <?php echo htmlspecialchars(json_encode($this->tasks)); ?>">
            <tr ng-repeat="task in tasks">
                 <td>{{task[1]}}</td>
                 <td>{{task[2]}}</td>
            </tr>
    </tbody>
</table>
<div class="col-xs-12 col-sm-6" ng-controller="FormController">
    <h2>Add New Task</h2>
    <form id="create-task" ng-submit="processForm()">
        <div class="form-group">
            <label for="todoName">Description</label>
            <input type="text" class="form-control" id="todoName" placeholder="Remember the milk" ng-model="formData.description">
        </div>
        <div class="form-group">
            <label for="todoDate">Due Date</label>
            <input type="text" class="form-control" id="todoDate" placeholder="2016-11-31" ng-model="formData.date">
        </div>
        <button type="submit" class="btn btn-default">Create Task</button>
    </form>
</div>
