<?php
    $this->headScript()->prependFile($this->basePath('js/index.js'))
?>
<h1>Tasks</h1>
<div class="col-xs-12 col-sm-3">
    <h2 id="save-task-hdr">Add New Task</h2>
    <form id="create-task" ng-submit="saveTask()">
        <div class="form-group">
            <label for="todoName">Description</label>
            <input type="text" class="form-control" id="todo-name" placeholder="Remember the milk" ng-model="formData.description" required>
        </div>
        <div class="form-group">
            <label for="todoDate">Due Date</label>
            <input type="text" class="form-control" id="todo-date" placeholder="2016-11-31" ng-model="formData.date" required>
        </div>
        <input type="hidden" id="todo-id" ng-model="formData.id">
        <button type="submit" class="btn btn-default">Create Task</button>
    </form>
</div>
<div class="col-xs-12 col-sm-offset-1 col-sm-8">
<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>Due Date</th>
            <th></th>
        <tr>
    </thead>
    <tbody ng-init="tasks = <?php echo htmlspecialchars(json_encode($this->tasks)); ?>">
            <tr ng-repeat="task in tasks">
                 <td>{{task[1]}}</td>
                 <td>{{task[2]}}</td>
                 <td><a ng-click="loadEditForm($index)">Edit</a></td>
            </tr>
    </tbody>
</table>
</div>
