<h1>Tasks</h1>
<ul>
    <li>Get Groceries</li>
    <li>Pick up Tickets</li>
    <li>Add New Task..</li>
</ul>
<div class="col-xs-12 col-sm-6">
    <h2>Add New Task</h2>
    <form>
        <div class="form-group">
            <label for="todoName">Name</label>
            <input type="text" class="form-control" id="todoName" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="todoDate">Due Date</label>
            <input type="text" class="form-control" id="todoDate" placeholder="Due Date">
        </div>
    </form>
</div>
